dist: xenial
sudo: false
latex: true
language: r
r: release

warnings_are_errors: false

cache:
  packages: true
  
apt_packages:
  - libgdal-dev
  - libudunits2-dev

r_packages:
  - rsconnect
  - shiny
  - tidyverse
  - kableExtra
  - mlr
  - rpart
  - rpart.plot
  - e1071
  - caret
  - smotefamily
  - FSelectorRcpp
  - randomForest
  - data.table
  - DT
  - shinythemes
  - ggplot2
  - plotly
  
script:
  - R -f deploy.R

 
